In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import  accuracy_score, roc_auc_score, roc_curve, confusion_matrix

In [3]:
Train_Data = pd.read_csv("Data/Train-Set.csv")
Test_Data = pd.read_csv("Data/Test-Set.csv")

In [4]:
Train_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54712 entries, 0 to 54711
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  54712 non-null  int64  
 1   id          54712 non-null  int64  
 2   age         54712 non-null  int64  
 3   job         54712 non-null  object 
 4   marital     54712 non-null  object 
 5   education   54712 non-null  object 
 6   default     54712 non-null  object 
 7   balance     31842 non-null  float64
 8   housing     54712 non-null  object 
 9   loan        54712 non-null  object 
 10  contact     54712 non-null  object 
 11  day         54712 non-null  object 
 12  month       54712 non-null  object 
 13  duration    54712 non-null  int64  
 14  campaign    54712 non-null  int64  
 15  pdays       54712 non-null  int64  
 16  previous    54712 non-null  int64  
 17  poutcome    54712 non-null  object 
 18  Target      54712 non-null  object 
dtypes: float64(1), int64(7), 

In [5]:
Train_Data.describe().T

count          mean           std     min       25%      50%  \
Unnamed: 0  54712.0  38925.687582  22553.956707     0.0  19414.75  38803.0   
id          54712.0  45173.763397  25935.559039     0.0  22737.75  45248.0   
age         54712.0     40.580147     10.544504    17.0     32.00     39.0   
balance     31842.0   1368.024590   3057.847866 -8019.0     73.00    449.0   
duration    54712.0    257.282260    255.270335     0.0    103.00    180.0   
campaign    54712.0      2.679961      2.966822     1.0      1.00      2.0   
pdays       54712.0    425.022829    476.813012    -1.0     -1.00     88.0   
previous    54712.0      0.407351      1.520253     0.0      0.00      0.0   

                 75%      max  
Unnamed: 0  58491.25  78160.0  
id          67581.25  89999.0  
age            48.00     98.0  
balance      1435.00  98417.0  
duration      318.00   4199.0  
campaign        3.00     58.0  
pdays         999.00    999.0  
previous        0.00     58.0

In [6]:
Train_Data.describe(include="object").T

count unique          top   freq
job        54712     12  blue-collar  12042
marital    54712      4      married  33095
education  54712     11    secondary  16357
default    54712      3           no  49368
housing    54712      3          yes  29666
loan       54712      3           no  45564
contact    54712      3     cellular  35134
day        54712     41          may   7636
month      54712     17          may   9651
poutcome   54712      5      unknown  26057
Target     54712      2           no  48433

In [7]:
Train_Data['job'].unique()

array(['blue-collar', 'management', 'technician', 'self-employed',
       'retired', 'admin.', 'unknown', 'student', 'services', 'housemaid',
       'entrepreneur', 'unemployed'], dtype=object)

In [8]:
Train_Data['marital'].unique()

array(['married', 'divorced', 'single', 'unknown'], dtype=object)

In [9]:
Train_Data['education'].unique()

array(['basic.9y', 'tertiary', 'high.school', 'primary', 'unknown',
       'basic.4y', 'university.degree', 'secondary',
       'professional.course', 'basic.6y', 'illiterate'], dtype=object)

In [10]:
Train_Data['age'].unique()

array([47, 48, 38, 50, 54, 59, 39, 28, 67, 34, 23, 27, 49, 33, 32, 62, 45,
       24, 52, 46, 57, 37, 40, 55, 30, 56, 31, 26, 58, 44, 53, 41, 42, 71,
       25, 35, 43, 19, 29, 60, 36, 70, 51, 61, 22, 65, 20, 69, 75, 63, 64,
       72, 66, 73, 76, 21, 78, 77, 74, 79, 81, 68, 84, 87, 80, 18, 82, 93,
       86, 95, 85, 88, 83, 98, 17, 92, 91, 90, 89], dtype=int64)

In [11]:
Train_Data['campaign'].unique()

array([ 2,  3,  1,  5, 13,  4,  7, 18,  8, 10, 14, 12,  6, 55, 17,  9, 11,
       15, 43, 20, 29, 16, 22, 19, 23, 32, 30, 21, 28, 25, 26, 41, 56, 27,
       35, 24, 36, 38, 31, 44, 50, 40, 34, 33, 58, 51, 37], dtype=int64)

In [12]:
Train_Data['contact'].unique()

array(['cellular', 'telephone', 'unknown'], dtype=object)

In [13]:
Train_Data['day'].unique()

array(['apr', '7', 'aug', '4', '29', 'may', '21', '14', 'nov', 'sep',
       'jul', 'mar', '15', '27', 'dec', '8', '28', '6', '22', '18', '12',
       '20', '5', '17', '11', 'jun', '10', '9', '30', '13', '16', '25',
       '2', '19', '26', '24', '23', '3', '1', '31', 'oct'], dtype=object)

In [14]:
Train_Data['default'].unique()

array(['no', 'yes', 'unknown'], dtype=object)

In [15]:
Train_Data['duration'].unique()

array([ 583,  725,   74, ..., 1397, 1558, 1250], dtype=int64)

In [16]:
Train_Data['housing'].unique()

array(['no', 'yes', 'unknown'], dtype=object)

In [17]:
Train_Data['loan'].unique()

array(['yes', 'no', 'unknown'], dtype=object)

In [18]:

Train_Data['previous'].unique()

array([ 1,  0,  9,  7,  6,  4,  3,  2,  5,  8, 10, 14, 16, 27, 11, 23, 12,
       15, 17, 13, 24, 19, 30, 20, 21, 18, 29, 25, 40, 28, 22, 37, 38, 51,
       26, 35, 58, 41], dtype=int64)

In [19]:
Train_Data['poutcome'].unique()

array(['failure', 'unknown', 'nonexistent', 'success', 'other'],
      dtype=object)

In [20]:
Train_Data['month'].unique()

array(['fri', 'apr', 'wed', 'may', 'thu', 'jan', 'jul', 'sep', 'tue',
       'mon', 'aug', 'nov', 'jun', 'oct', 'feb', 'mar', 'dec'],
      dtype=object)

In [21]:

# Function to check and correct day and month values
def check_and_correct_date(row):
    valid_days = list(map(str, range(1, 32)))  # Assuming days range from 1 to 31
    valid_months = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
    if row['day'] not in valid_days or row['month'] not in valid_months:
        # Incorrect day or month value found, swap them
        row['day'], row['month'] = row['month'], row['day']
    return row


In [22]:
Train_Data = Train_Data.apply(check_and_correct_date, axis=1)


In [23]:
Train_Data['month'].unique()

array(['apr', 'aug', 'may', 'jan', 'jul', 'sep', 'nov', 'mar', 'dec',
       'jun', 'oct', 'feb'], dtype=object)

In [24]:
Train_Data['day'].unique()

array(['fri', '7', 'wed', '4', 'thu', '29', '21', '14', 'tue', 'mon',
       '15', '27', '8', '28', '6', '22', '18', '12', '20', '5', '17',
       '11', '10', '9', '30', '13', '16', '25', '2', '19', '26', '24',
       '23', '3', '1', '31'], dtype=object)

In [25]:
Test_Data = Test_Data.apply(check_and_correct_date, axis=1)


In [26]:
Train_Data.drop(columns='balance',axis=1)
Test_Data.drop(columns='balance',axis=1)
Train_Data.drop(columns='id',axis=1)
Train_Data.drop(columns='Unnamed: 0',axis=1)
Test_Data.drop(columns='id',axis=1)
Test_Data.drop(columns='Unnamed: 0',axis=1)

id  age          job   marital          education default  balance  \
0      74249   34       admin.   married  university.degree      no      NaN   
1      35779   31   management    single           tertiary      no    165.0   
2      66769   28  blue-collar    single           basic.9y      no      NaN   
3      27888   57       admin.  divorced          secondary      no   1878.0   
4      63306   55   management  divorced           tertiary      no    277.0   
...      ...  ...          ...       ...                ...     ...      ...   
23444    902   36  blue-collar   married           basic.6y      no      NaN   
23445  39745   44     services   married          secondary      no    133.0   
23446  40150   31  blue-collar   married           basic.9y      no      NaN   
23447   6012   43   management  divorced        high.school      no      NaN   
23448  61584   29     services    single        high.school      no      NaN   

      housing loan    contact  day month  duration  campaign  pdays  previous  \
0          no   no   cellular  wed   jul       266         1    999         0   
1          no  yes   cellular    8   aug       523         2     -1         0   
2          no   no  telephone  fri   may       489         2    999         0   
3         yes   no   cellular   17   nov       219         1     -1         0   
4          no   no   cellular   12   aug       101         3     -1         0   
...       ...  ...        ...  ...   ...       ...       ...    ...       ...   
23444      no   no  telephone  fri   may       203         5    999         0   
23445      no   no   cellular   29   jan       202         3     -1         0   
23446     yes   no   cellular  wed   jul       590         1    999         0   
23447     yes   no   cellular  mon   nov       488         2    999         0   
23448     yes   no  telephone  thu   may        93         1    999         0   

          poutcome  
0      nonexistent  
1          unknown  
2      nonexistent  
3          unknown  
4          unknown  
...            ...  
23444  nonexistent  
23445      unknown  
23446  nonexistent  
23447  nonexistent  
23448  nonexistent  

[23449 rows x 17 columns]

In [27]:
Test_Data.head()

Unnamed: 0     id  age          job   marital          education default  \
0       45247  74249   34       admin.   married  university.degree      no   
1       19894  35779   31   management    single           tertiary      no   
2       70048  66769   28  blue-collar    single           basic.9y      no   
3       24241  27888   57       admin.  divorced          secondary      no   
4       20495  63306   55   management  divorced           tertiary      no   

   balance housing loan    contact  day month  duration  campaign  pdays  \
0      NaN      no   no   cellular  wed   jul       266         1    999   
1    165.0      no  yes   cellular    8   aug       523         2     -1   
2      NaN      no   no  telephone  fri   may       489         2    999   
3   1878.0     yes   no   cellular   17   nov       219         1     -1   
4    277.0      no   no   cellular   12   aug       101         3     -1   

   previous     poutcome  
0         0  nonexistent  
1         0      unknown  
2         0  nonexistent  
3         0      unknown  
4         0      unknown